version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - segel

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${USER_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${USER_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      - segel

  web:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    networks:
      - segel

networks:
  segel:
    driver: bridge
